language: java

sudo: required

jdk:
  - oraclejdk8

install: true

addons:
  sonarcloud:
    organization: "hedgedoge21490-github"
    token: $BatBatToken

#script:
#  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
#  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
#  - sudo apt-get update && sudo apt-get install oracle-java8-installer
#  - java -version

notifications:
  email:
    on_success: never
    on_failure: always

